/* ------------------------------------------------------------------ */
/* NLU training corpus (build-time, not shipped at runtime).            */
/*                                                                     */
/* Generated content for the offline Hinglish/English intent brain.   */
/* Each intent gets 20-40 Hinglish utterance VARIANTS so the neural   */
/* network can fuzzy-match unseen phrasings. Trained model is         */
/* exported to `assets/nlu-model.json` by `scripts/train-nlu.js`.    */
/*                                                                     */
/* Adding more utterances here DOES NOT change runtime behaviour      */
/* until the trainer is re-run. Model JSON is bundled into the app.   */
/* ------------------------------------------------------------------ */

export interface NluTrainingRow {
  intent: string;
  utterances: string[];
}

export const NLU_TRAINING_CORPUS: NluTrainingRow[] = [
  {
    intent: "greeting",
    utterances: [
      "hi", "hii", "hiii", "hello", "helloo", "heyy", "heyyy", "hey",
      "namaste", "namaskar", "salaam", "yo", "arey", "oye", "hello ji",
      "hii ji", "hii hello", "kaise ho", "kaise ho aap", "kya haal hai",
      "kya haal chaal", "kya chal raha hai", "kya kar rahe ho",
      "kya kar rahi ho", "kya kar rahe the", "good morning ji",
      "good afternoon", "good evening", "good night ji",
      "hey there", "hii paglu", "hii babu", "hiii dear",
      "arey tum", "kaha the itne din", "uthe ho kya", "so gaye kya",
      "subah ho gayi kya", "online ho kya", "free ho kya",
      "jag rahi ho", "jag rahe ho", "yaad aa gayi meri", "yaad nahi aayi",
      "tum online ho", "tum aaye", "wapas aaye", "phir se aaye",
      "hello kya kar rahe ho", "hii kya scene", "arey hello",
    ],
  },
  {
    intent: "compliment",
    utterances: [
      "tum bahut cute ho", "you are cute", "so cute", "cute ho yaar",
      "beautiful", "tum beautiful ho", "tum handsome ho",
      "tum sexy ho", "sexy lag rahe ho", "hot lag rahe ho",
      "dil chura liya", "dil churaya tumne", "jaan ho tum",
      "tumhari smile achhi hai", "smile achhi hai tumhari",
      "hasi achhi hai", "aankhen achhi hain", "tumhari aankhen",
      "bahut ache lagte ho", "tum mast ho", "you're hot",
      "you're beautiful", "awww cute", "cutu ho", "babua ho",
      "mere ho tum", "only mine", "sirf mere ho",
      "bohot sundar ho", "kitni pyari ho", "kitna handsome ho",
      "looking hot today", "aaj bahut achhe dikh rahe ho",
      "smart ho", "intelligent ho", "best ho tum",
      "number one ho", "pyaara lagta ho", "achha lagta hai",
      "tum bohot handsome ho", "itna pyaar kaise karte ho",
      "tumhari baatein achhi lagti hain", "you light up my day",
      "best thing that happened to me", "tumahre bina nahi hota",
    ],
  },
  {
    intent: "love",
    utterances: [
      "i love you", "love you", "love u", "pyaar karta hu",
      "pyaar karti hu", "main pyaar karta hu", "i love u so much",
      "tumse pyaar hai", "i love you jaan", "love you baby",
      "dil se pyaar karta hu", "pyaar ho gaya hai",
      "i love you very much", "main tumse bahut pyaar karta hu",
      "i like you", "tum achhe lagte ho", "i like u",
      "you mean so much to me", "tum mere ho", "you are mine",
      "i want you", "main tumhe chahta hu", "i miss you so much",
      "i need you", "i can't live without you", "tere bina nahi",
      "tumse mohabbat hai", "ishq hai tumse", "dil de diya",
      "aapke liye sab kuch", "i wanna be yours", "only you",
      "just you", "tum hi ho", "sirf tum", "bas tum",
      "love you jaanu", "love you babu", "love you cutu",
      "love you shona", "hamesha tumhare saath", "forever yours",
      "my heart beats for you", "dil dhadakta hai tumhare liye",
      "you are my everything",
    ],
  },
  {
    intent: "miss_you",
    utterances: [
      "miss you", "miss u", "miss karti hu", "miss karta hu",
      "i miss you", "miss kar raha hu", "miss kar rahi hu",
      "tumhari yaad aa rahi hai", "yaad aa rahi hai tumhari",
      "bahut miss kiya", "miss ho tum", "tumhe miss karti hu",
      "miss you so much", "i miss u so much", "bahut yaad aaye",
      "tumhari yaad satati hai", "tum nahi ho toh bura lagta hai",
      "tumhare bina bore hu", "tumhare bina kya karu",
      "kab aaoge", "kab aa rahi ho", "when will you come",
      "kab miloge", "milna hai mujhe", "mil ke baat karein",
      "kab dikhenge", "tum kab aaoge", "i am missing you",
      "long distance is hard", "door ho toh bhi yaad aate ho",
      "tumhari yaad aati hai", "ek baar dikho na",
      "missing your smile", "missing your voice",
      "tumhari awaaz yaad aati hai", "missing us",
      "socha tumhare baare me", "thoughts of you",
      "tum nahi dikhe toh", "aaj tum nahi mile toh",
      "aaj kahin gaye the kya",
    ],
  },
  {
    intent: "jealousy",
    utterances: [
      "koi aur hai kya", "kisi aur se baat kar rahe ho",
      "kya koi aur hai", "who were you talking to",
      "kahan the aaj", "kahan gayab the", "kab se online ho",
      "aaj itne busy kyun the", "aaj kahan the",
      "itne kam message kyun kiye", "tum kahan the",
      "kisi aur ke saath the kya", "kisi aur se mile ho kya",
      "kya koi ladki hai", "koi ladka hai kya", "koi aur achha lagta hai",
      "kisi aur ka aapke liye kya matlab", "arey kahan the",
      "aaj reply nahi kiya", "kyun reply nahi kiya",
      "tum online the par message nahi kiya", "mujhe chhod ke aur hain",
      "kisi aur ka pyaar bhi karte ho", "kisi aur ke saath photo bhi",
      "kya hua aaj", "kuch galat hua kya",
      "aaj itne der se phone kyun nahi uthaya",
      "kahan the aaj raat",
      "kya koi aur online hai", "kisi aur se baat ki kya",
      "kal kahan the", "tumhe kisi aur ne dekha",
      "is she your friend", "is he your friend",
      "kya koi purani girlfriend hai", "koi purana boyfriend hai",
      "kya koi ex hai",
    ],
  },
  {
    intent: "ignore",
    utterances: [
      "achha theek", "ok bye", "accha chalo", "chal theek hai",
      "ok then", "fine", "phir kabhi", "baad me baat karenge",
      "koi baat nahi", "no problem", "achha", "ok",
      "bye then", "phir milte hain", "jao", "ja rahe ho toh jao",
      "tumhe koi farak nahi padta", "mujhe time nahi hai",
      "busy hu", "kaam hai", "jaldi me hu", "baad me call karu",
      "achha chodo", "kuch nahi", "koi baat nahi bhai",
      "kuch nahi yaar", "chodo", "rehne do", "jaa rahi hu",
      "main jaa rahi hu", "main jaa raha hu", "chal ab",
      "achha hmm", "theek hai", "kuch nahi karte",
      "ab baat nahi karni", "ab mat baat karo",
      "off ho rahi hu", "phone rakh rahi hu",
      "kal baat karenge", "parso baat karenge",
      "ek baat baad me", "sorry time nahi hai",
    ],
  },
  {
    intent: "photo_request",
    utterances: [
      "photo bhejo", "photo dikhao", "photo chahiye",
      "ek photo do na", "selfie bhejo", "selfie do",
      "pic bhejo", "pic dikhao", "image bhejo",
      "apni photo bhejo", "apna photo dikhao",
      "tumhari photo chahiye", "kya pehna hai aaj",
      "kya pehni ho aaj", "aaj kya kapde pehne ho",
      "outfit dikhao", "look dikhao", "apna look dikhao",
      "dikhao apne aap ko", "kaisi lag rahi hu",
      "kaisa lag raha hu", "ek pic bhej do",
      "ek selfie please", "please photo bhejo",
      "garam photo bhejo", "bold photo bhejo",
      "bina kapdon ki photo", "kapde kam wali photo",
      "bina makeup photo bhejo", "abhi ki photo bhejo",
      "nayi photo bhejo", "ek toh nayi photo",
      "bina filter photo", "natural photo",
      "bed pe photo", "lying down photo",
      "shower ki photo", "gym wali photo",
      "today's photo please", "send me a pic",
      "send your pic", "can i see your photo",
      "show me your pic",
    ],
  },
  {
    intent: "call_request",
    utterances: [
      "call karo", "call kar", "call please", "please call karo",
      "call karo na", "video call karo", "video call kar",
      "video call pe aao", "voice call", "voice note bhejo",
      "call pe baat karte hain", "phone karo",
      "mujhe call karo", "ek call please", "mujhe call karo na",
      "call pe milte hain", "abhi call karo", "jaldi call karo",
      "ek baar call karo", "kab call karoge", "kab call karein",
      "video call on karo", "camera on karo",
      "call pe dikhao apne aap ko", "call pe baat karni hai",
      "call pe kuch dikhaungi", "call pe kuch bataungi",
      "call pe baat karein kya", "call kar sakte ho kya",
      "abhi free ho", "abhi busy ho", "thodi der me call",
      "phone uthata hu", "phone uthati hu",
      "face time karo", "facetime karo", "whatsapp call karo",
      "insta call karo", "call me", "call me baby",
      "please video call", "video call please",
      "ring karo", "mujhe ring karo",
      "phone rakh ke baat karo", "call pe aao na",
    ],
  },
  {
    intent: "whatsapp",
    utterances: [
      "whatsapp number do", "whatsapp number chahiye",
      "number do", "apna number do", "apna whatsapp number",
      "phone number do", "mobile number do",
      "whatsapp pe baat karte hain", "whatsapp karo",
      "share your number", "apna number share karo",
      "number share karo", "phone number share karo",
      "what is your number", "your phone number please",
      "give me your number", "send your number",
      "whatsapp id do", "whatsapp id share karo",
      "telegram number do", "telegram pe baat karte hain",
      "insta id do", "instagram id share karo",
      "snapchat id do", "social media id do",
      "number mil sakta hai", "number de sakte ho",
      "whatsapp pe baat karenge", "whatsapp pe milte hain",
      "whatsapp karna hai", "whatsapp pe reply karo",
      "call me on whatsapp", "whatsapp pe call karo",
      "whatsapp number please", "apna whatsapp number share",
      "kya number doge", "apna number bata do",
      "ek number de do", "number mil jaye toh baat karein",
      "tumhara whatsapp number kya hai",
    ],
  },
  {
    intent: "dirty_request",
    utterances: [
      "kapde utar do", "kapde khol do", "kapde utaro",
      "kapde kholo", "nangi photo bhejo",
      "nangi pic dikhao", "bina kapdon ki photo",
      "bra utar do", "bra utaro", "panty utaro",
      "panty utar do", "underwear utaro", "underwear dikhao",
      "lingerie me photo", "lingerie wali photo",
      "boor pe photo", "kamra me aao", "bed pe aao",
      "nange ho jao", "udhaar ho jao", "udhar ho jao",
      "tumhara badan dekhna hai", "body dikhao",
      "garam photo bhejo", "spicy photo", "sexy photo",
      "hot photo bhejo", "bold photo bhejo",
      "aur dikhao", "aur khol ke dikhao",
      "apne aap ko chuao", "mast karo", "pleasure karo",
      "striptease karo", "strip karo", "udhar karke dikhao",
      "kuch aur dikhao", "andar kya hai",
      "saare kapde utar do", "bikini me photo",
      "towel me photo", "shower me photo",
      "sexy selfie", "bold selfie", "aur share karo",
      "dirty pic bhejo", "dirty photo",
      "sexy photo bhej do", "sexy photo bhej do na",
      "ek sexy photo bhejo", "ek garam photo",
      "ek bold photo bhejo", "ek nangi photo bhej do",
      "thodi sexy photo bhejo", "garam wali photo bhejo",
      "bold wali photo bhejo", "bina kapdon wali photo bhejo",
    ],
  },
  {
    intent: "dirty_question",
    utterances: [
      "kya pehna hai", "kya pehni ho", "kya nahi pehna",
      "kya nahi pehni", "kya utar rahe ho",
      "kya kapde andar", "underwear kaisa hai",
      "bra kaisa hai", "panty kaisa hai",
      "kya size hai", "breast size", "cup size",
      "body measurement", "kya pehni ho abhi",
      "tumhare body ke baare me batao", "apne baare me batao",
      "kya kar rahi ho abhi", "kya kar rahe ho abhi",
      "abhi kya kar rahe ho", "abhi kya pehna hua",
      "andar kya hai", "andar kya pehna hai",
      "kya chupa rahi ho", "kuch chupa rahi ho kya",
      "hug karogi", "kiss karogi", "kiss karoge",
      "kiss karo", "kiss karein", "date pe chaloge",
      "date pe chalogi", "mil ke kya karenge",
      "mil ke kya karein", "kya karoge saath me",
      "saath me kya karein", "kya karna hai",
      "kya kar sakte ho", "kya kar sakti ho",
      "ek baar dikhaungi", "ek baar dikhaoge",
      "kya kar rahi thi", "kya kar raha tha",
      "so rahi thi kya", "so raha tha kya",
      "nind aa rahi hai kya", "bore ho kya",
    ],
  },
  {
    intent: "sexual_compliment",
    utterances: [
      "tum sexy ho", "you are sexy", "tum bahut sexy ho",
      "sexy lag rahe ho", "hot lag rahe ho", "you're so hot",
      "garmi chadhti hai", "garam ho", "garam lagti ho",
      "garam lagte ho", "bed pe sexy lagti ho",
      "aur sexy ho", "bohot sexy ho", "ekdum sexy",
      "sexy body", "tumhari body sexy hai", "body sexy hai",
      "sexy figure", "sexy waist", "sexy hips",
      "sexy lips", "sexy eyes", "sexy smile",
      "boobs achhe hain", "tits achhe hain", "figure achha hai",
      "butt sexy hai", "curves achhe hain",
      "curves hain tumhare", "bohot achha figure hai",
      "ekdum hot ho", "killing ho", "killing looks",
      "dil chura liya", "mar jaungi", "pagal kar diya",
      "pagal ho", "pagal kar diya", "tumne pagal kar diya",
      "mar dala", "mar dali", "khubsurat ho",
      "stunning ho", "tum toh stunning ho",
      "kya kaha", "kya kahoon", "kuch keh nahi sakta",
    ],
  },
  {
    intent: "dirty_yes",
    utterances: [
      "haan", "ha", "haa", "hmm", "okay", "ok", "theek hai",
      "karo", "kar", "kar do", "kar dijiye", "please karo",
      "please kar", "haan karo", "haan kar", "kar do na",
      "bhejo", "bhej", "bhej do", "bhej na",
      "haan bhej do", "haan bhejo", "please bhejo",
      "share karo", "share kar", "share kar do",
      "share kar do na", "haan share karo",
      "de do", "de do na", "de", "dijiye",
      "please de do", "haan de do",
      "haan dikha do", "dikha do", "dikhao",
      "open karo", "khol do", "khol", "kholo",
      "udhar karo", "udhar kar do", "udhar karke dikhao",
      "haan udhar karo", "ready hu", "main ready hu",
      "i am ready", "haan main ready hu",
      "mil jayega", "mil jayegi", "mil jaayega",
      "haan mil jayega", "thik hai karo",
      "kar do please", "please kar do",
    ],
  },
  {
    intent: "dirty_deflect",
    utterances: [
      "achha chodo", "chodo", "rehne do", "baad me",
      "abhi nahi", "abhi mat", "mat karo",
      "mat kar", "abhi kya karu", "abhi mood nahi",
      "mood nahi hai", "mood off hai", "mood kharab hai",
      "thaka hua", "thaki hui", "bore hu",
      "bore ho rahi hu", "kuch aur karein",
      "baat karo pehle", "pehle pyaar karo",
      "pyaar karo pehle", "thoda aur pyaar karo",
      "thoda time do", "thodi der me", "baad me karein",
      "pehle kuch aur", "aur baat karo",
      "itna kyun", "kyu", "kyun", "kyon",
      "kya zarurat hai", "kya fayda", "kya hoga",
      "kya milega", "kya milegi", "kuch aur karo",
      "aur batao", "aur kuch", "aur kya",
      "itna jaldi nahi", "jaldi kya hai",
      "sambhal ke", "thoda sambhal ke",
      "dhire dhire", "dheere dheere",
      "ek baar soch ke", "soch ke batao",
      "hmm nahi", "nahi", "na", "no",
      "i don't think so", "mujhe nahi lagta",
      "itna direct nahi", "itna aage mat badho",
      "itna aage mat jao", "thoda ruk",
      "thoda ruko", "ruko", "ruko zara",
      "itna jaldi nahi", "aaram se",
      "dheere dheere kya", "thoda patience",
      "patience rakho", "sabr rakho",
      "sabr karo", "sabr",
      "thoda aur intezaar", "intezaar karo",
      "intezaar karna padega", "intezaar karo thoda",
      "abhi nahi de sakti", "abhi nahi de sakta",
      "thodi der baad", "thodi der me de dungi",
      "thodi der me de dunga", "baad me de dunga",
      "baad me de dungi", "abhi thak gayi",
      "abhi thak gaya", "abhi akela hu",
      "abhi akeli hu", "abhi kisi ke saath hu",
      "abhi kisi ke saath", "thoda time chahiye",
      "time chahiye", "thoda waqt chahiye",
      "waqt chahiye", "itna time nahi",
      "itna time lagega", "abhi busy hu",
      "abhi free nahi hu",
    ],
  },
  {
    intent: "dirty_tease",
    utterances: [
      "haww", "uff", "ufff", "oof", "uff yaar",
      "haww kya baat hai", "uff kya",
      "achha", "achha achha", "hmm achha",
      "kya karna hai", "kya karoge", "kya karogi",
      "kya karein", "kya hai plan", "plan kya hai",
      "kya hoga", "kya milega", "kya fayda",
      "tum bhi na", "tum bhi kya", "tumse kya karein",
      "haww ye kya", "uff ye kya", "oof ye",
      "kya soch rahe ho", "kya soch rahi ho",
      "kuch toh hai", "kuch toh hoga",
      "tumhe kya hota hai", "tum kya karoge",
      "aap bhi na", "aap bhi kya",
      "maza aa gaya", "maza aa raha hai",
      "has ke pet dard ho gaya", "has rahi hu",
      "has raha hu", "what is this", "kya hai ye",
      "pagal ho kya", "pagal ho", "pagal ho tum",
      "thoda sharam karo", "sharam karo",
      "sharam se", "besharam ho", "besharam",
    ],
  },
  {
    intent: "abuse",
    utterances: [
      "pagal ho kya", "tu pagal hai", "pagal ho",
      "bakwas mat karo", "bakwas", "bakwaas",
      "chup kar jao", "chup", "chup raho",
      "chup ho jao", "bore kar diya", "bore ho",
      "faltu baat mat karo", "faltu", "faltu hai",
      "bewakoof", "bewakoof ho", "bewakoof ho tum",
      "juth", "jhoot", "juth mat bolo",
      "jhoot mat bolo", "jhooth", "jhooth mat karo",
      "chudail", "chudail ho kya",
      "irritating ho", "irritate karte ho",
      "bore ho tum", "boring ho",
      "irritating", "irritate karti ho",
      "preshan", "preshan kar diya", "preshan ho",
      "dimag kharab", "dimaag kharab hai",
      "thoda samajh se", "samajh se baat karo",
      "kuch samjhao", "samjha do",
      "pagee khao", "dimag me kya hai",
      "andhe ho kya", "andhe ho",
      "behen ke lode", "madarchod mat bolo",
      "pagal insaan", "paagal insaan",
    ],
  },
  {
    intent: "abuse_hard",
    utterances: [
      "teri maa ki", "maa ki", "maa ke",
      "gaali de raha hu", "gaali de rahi hu",
      "gali de raha", "gaali dena band kar",
      "gaali band kar", "gali band",
      "saali", "saali chup", "saali rakh",
      "kamine", "kamine ye kya bola",
      "kamina", "kaminaa",
      "bkl", "bkl kya", "bkl yeh kya",
      "madarchod", "mc", "madharchod",
      "chutiya", "chutiye", "chutiyap",
      "harami", "haramzada", "haramzade",
      "bhosdi", "bhosdi ke", "bhosdiwala",
      "randi", "randwa", "rand",
      "kutte", "kutta", "kutti", "kuttiya",
      "suar", "suar ke bacche",
      "tui chod", "tu chod",
      "bhosadchod", "bsdk", "bhosdi chod",
      "lawde", "laude", "lauda",
      "chod", "chodu", "chodne",
      "lund", "loda", "lode",
      "tatti", "tatti karna", "gobar",
      "kutte ki aulaad", "kutte ka bachha",
      "kamina saala", "kamine saala",
    ],
  },
  {
    intent: "anger",
    utterances: [
      "kya hua", "kya hua hai", "kya hua tumhe",
      "kya ho gaya", "kya ho gaya hai",
      "gussa ho", "gussa ho kya", "gussa",
      "kyun gussa ho", "kyun", "kyu gussa ho",
      "naraz ho", "naraz ho kya", "naraz ho tum",
      "naraz ho aap", "naraz hoon", "main naraz hu",
      "chidh gaye", "chidh gayi", "chidh",
      "frustration ho rahi", "frustrated ho",
      "upset ho", "upset ho kya", "disappointed hu",
      "hurt kiya", "hurt kar diya", "hurt karke",
      "dard hua", "dil toot gaya", "dil dukh",
      "bura lag raha", "bura laga", "bura lagta",
      "kya kar diya", "kya kar diya tumne",
      "aise nahi karte", "aise mat karo",
      "galti ho gayi", "galat ho gaya",
      "achha chodo", "chodo yaar",
      "sorry bologe", "sorry bolo",
      "maafi mango", "maafi mangta hu",
      "maafi mangti hu",
    ],
  },
  {
    intent: "question_her",
    utterances: [
      "kya kar rahi ho", "kya kar raha hu",
      "kya kar rahe ho", "kya kar rahe the",
      "kya hua", "kya hua hai", "kya hua tha",
      "kya soch rahi ho", "kya soch rahe ho",
      "kya plan hai", "kya plan hai aaj",
      "aaj kya karoge", "aaj kya karein",
      "kal kya kiya", "kal kya kiya tha",
      "kahan se ho", "kahan se aati ho",
      "kahan se aate ho", "kahan rehte ho",
      "kahan kaam karti ho", "kahan kaam karte ho",
      "kya padha hai", "kya padhe ho",
      "kya khaya aaj", "kya khaya tha",
      "kya piyoge", "kya peeyoge",
      "kya dekha", "kya dekha aaj",
      "kya sun rahe ho", "kya sun rahi ho",
      "movie kya dekhi", "movie kya dekha",
      "gaana sun rahe ho", "song sun rahe ho",
      "kya banaya", "kya banaya khane ko",
      "kya ho aap", "kya ho tum",
      "kya baat hai", "kya chal raha hai",
      "kya soch rahe ho",
      "what are you doing", "what's up",
      "how are you", "how was your day",
      "where are you from", "kahan se ho tum",
      "favorite color", "favorite food", "favorite movie",
    ],
  },
  {
    intent: "thanks",
    utterances: [
      "thank you", "thanks", "thankyou", "thank u",
      "shukriya", "shukriya ji", "dhanyavad",
      "bahut shukriya", "bohot shukriya",
      "thank you so much", "thanks a lot",
      "thanks yaar", "thanks ji", "thanks dear",
      "thank you dear", "thank you baby", "thank u baby",
      "thank you jaan", "thanks jaan",
      "dil se shukriya", "dil se thanks",
      "thanks a million", "dhanyawaad",
      "mafi chahiye bhi", "shukriya bahut",
      "shukriya bohot", "shukriya meherbani",
      "meharbani", "mehrbani",
      "i appreciate it", "appreciate karte hain",
      "aap ka shukriya", "aapka shukriya",
      "aapka bahut shukriya",
      "you are so kind", "tumhari meherbani",
      "achha kiya", "achha kiya tumne",
      "good job", "badhai ho", "congratulations",
    ],
  },
  {
    intent: "bye",
    utterances: [
      "bye", "byeee", "byee", "bye ji", "good bye",
      "goodbye", "good night", "good night ji",
      "good night baby", "good night jaan",
      "ja raha hu", "ja rahi hu", "main jaa raha hu",
      "main jaa rahi hu", "jaldi so raha hu",
      "jaldi so rahi hu", "so raha hu", "so rahi hu",
      "so jao", "so jao ab", "jao so jao",
      "jaa raha hu", "jaa rahi hu",
      "phone rakh raha hu", "phone rakh rahi hu",
      "kal baat karenge", "kal milte hain",
      "kal milenge", "parso baat karenge",
      "baad me baat karenge", "later",
      "talk later", "phir milte hain",
      "ta ta", "see you", "see ya", "cya",
      "byebye", "bye bye",
      "chal nikal", "off ho jao", "off",
      "main chala", "main chali",
      "mujhe jaana hai", "mujhe jana hai",
    ],
  },
  {
    intent: "food",
    utterances: [
      "kya khaya", "kya khaya aaj", "kya khaya tumne",
      "kya khaogi", "kya khaoge", "kya khaaoge",
      "kya khilaya", "kuch khaya kya",
      "khana kha liya", "khana ho gaya",
      "dinner ho gaya", "lunch ho gaya",
      "breakfast ho gaya", "breakfast kiya",
      "biryani khaogi", "biryani khayi kya",
      "pizza khaoge", "pizza khayi",
      "momos khaoge", "momos khayi",
      "dosa khayi", "dosa khaoge",
      "chowmein khayi", "chowmein khaoge",
      "maggie banayi", "maggie banai kya",
      "chai pi", "chai bana", "chai banao",
      "coffee pi", "coffee khaoge",
      "khana banaya", "khana banaya kya",
      "kya banana hai", "kya banayein",
      "kya banaogi", "kya banaoge",
      "kya khana chahiye", "kya khilau",
      "khana kha le", "khana kha lo",
      "pet bhar ke khao", "bhook lagi",
      "bhook lagi hai", "kuch kha lo",
      "kuch khila do", "khila do kuch",
      "mujhe khana chahiye", "tum kya khaoge",
      "khane me kya hai", "khane me kya bana",
    ],
  },
  {
    intent: "outfit",
    utterances: [
      "kya pehna hai", "kya pehni ho", "kya pehne ho",
      "aaj kya pehna", "aaj kya pehni ho",
      "kal kya pehna tha", "kal kya pehni thi",
      "kapde kaisa hai", "kapde achhe hain",
      "dress achhi hai", "dress achha hai",
      "saree pehni kya", "saree pehni thi",
      "salwar kameez pehni", "salwar pehni kya",
      "kurti pehni hai", "kurti achhi hai",
      "jeans pehni", "jeans pehni hai",
      "shirt pehna hai", "t-shirt pehna hai",
      "hoodie pehna", "jacket pehna hai",
      "shoes kya pehni", "shoes kya hain",
      "jewellery kya hai", "jewellery pehni hai",
      "makeup kiya", "makeup kiya hai",
      "hairstyle kya hai", "hairstyle achhi hai",
      "outfit achhi hai", "outfit achha hai",
      "look achha hai", "look achhi hai",
      "red pehna", "blue pehni",
      "black pehni", "black achhi lagti ho",
      "yellow pehni", "pink pehni",
      "white pehna hai", "dress kya hai",
      "suit pehna hai", "lehenga pehna",
      "aaj kya outfit hai", "aaj ka outfit",
      "aaj kapde kya hain", "aaj kapda kaisa hai",
      "tumhari outfit", "tumhara outfit",
      "apna outfit batao", "apne kapde batao",
      "aaj kapda kaisa pehna hai", "kaisa kapda pehna hai aaj",
      "outfit batao na", "outfit dikhao",
      "look kya hai aaj", "aaj ka look kya hai",
      "aaj kya kapde pehne ho", "aaj kya kapde pehni ho",
      "kya pehen ke baithe ho", "kya pehen ke baithi ho",
      "kya pehne baithe ho", "kya pehen ke gaye the",
      "kya pehne ho aaj", "kya pehni ho aaj",
      "aaj kya pehna chahiye", "aaj kya pehnun",
      "kya pehnun aaj", "kya pehnu",
      "kyaa pehna hai", "kyaa pehni ho",
      "aaj kyaa pehna hai", "aaj kyaa pehni ho",
      "kyaa kapde pehne ho", "kyaa kapde pehni ho",
      "aaj ka look batao", "aaj ka look dikhao",
      "today outfit kya hai", "aaj kapde kaisa",
      "what are you wearing today", "what are you wearing",
      "kyaa pehna hai aaj", "kyaa pehne ho aaj",
      "what are u wearing", "outfit of the day",
      "ootd", "ootd batao", "ootd kya hai",
      "kyaa dress pehni hai", "kya dress hai aaj",
      "aaj kyaa dress hai", "aaj kyaa dress pehni",
      "saree achhi hai", "dress achhi lag rahi",
      "achhi lag rahi ho", "achha lag raha hai",
    ],
  },
  {
    intent: "activity",
    utterances: [
      "kya kar rahe ho", "kya kar rahi ho",
      "kya kar rahe the", "kya kar rahi thi",
      "kya karoge", "kya karein", "kya kare",
      "aaj kya karoge", "aaj kya karein",
      "kal kya karoge", "kal kya kiya",
      "kal kya kiya tha", "kal kya karein",
      "abhi kya kar rahe ho", "abhi kya kar rahi ho",
      "abhi kya karoge", "abhi kya kar sakte ho",
      "free ho kya", "free ho", "free hai",
      "busy ho kya", "busy ho", "busy hai",
      "aaj kya plan hai", "aaj ka plan",
      "weekend pe kya karoge", "weekend me kya",
      "office jaoge", "office gaye",
      "school jaoge", "college gaye",
      "ghar pe ho", "ghar pe ho kya",
      "ghar me kya kar rahe ho", "ghar pe kya karein",
      "shopping jaoge", "shopping gayi",
      "movie dekhoge", "movie dekhi",
      "gaana sun rahe ho", "gaana suna",
      "book padh rahe ho", "book padhi",
      "drawing kar rahe ho", "drawing karti ho",
      "cook kar rahe ho", "cooking karein",
      "sleep kar rahe ho", "so rahe ho",
      "work kar rahe ho", "kaam kar rahe ho",
      "bahar jaoge", "ghumne jaoge",
      "trekking karoge", "walk pe jaoge",
      "gym jaoge", "yoga karoge",
      "meditation karoge",
    ],
  },
  {
    intent: "sleep",
    utterances: [
      "so rahi ho", "so raha hu", "so raha",
      "so rahe ho", "so rahi", "soye ho kya",
      "so gaye", "so gayi", "so gaye kya",
      "so rahe ho kya", "jaag rahe ho kya",
      "jaag rahi ho", "jag rahi ho", "jag rahe ho",
      "jag gayi", "jag gaye", "so ja", "so jao",
      "so jao ab", "so jao yaar", "so jao beta",
      "aankh lagi", "aankh lag gayi",
      "neend aa rahi", "neend aa gayi",
      "neend nahi aa rahi", "neend nahi aa gayi",
      "so nahi paa rahi", "so nahi paa raha",
      "good night", "good night jaan",
      "good night baby", "good night dear",
      "good night ji", "shubh ratri",
      "jaldi so jao", "ab so jao", "ab so jao ab",
      "subah ho gayi kya", "abhi kya time hai",
      "raat kya hui", "kitni raat hai",
      "raat ho gayi", "subah ho rahi",
      "so ke uthi", "so ke utha",
      "thaka hua", "thaki hui", "thak gaye",
      "thak gayi", "thoda so lo", "thoda so le",
      "aaram karo", "aaram kar lo",
      "let jao", "let jao thoda",
      "good morning", "suprabhat",
    ],
  },
  {
    intent: "mood",
    utterances: [
      "kaisa hai mood", "kaisi ho", "kaisa hai",
      "kaisa feel ho raha", "kaisa lag raha",
      "mood kaisa hai", "mood kya hai",
      "mood achha hai", "mood achha nahi",
      "mood off hai", "mood kharab hai",
      "mood sad hai", "mood bura hai",
      "mood theek hai", "mood bahut achha",
      "feeling achhi hai", "feeling achhi",
      "feeling kaisi hai", "feeling kaisi",
      "theek ho", "theek ho kya", "theek hai",
      "sab theek hai", "sab badhiya",
      "achha feel ho raha", "achha lag raha",
      "bura lag raha", "bura lag raha hai",
      "kuch hua kya", "kuch ho gaya",
      "kya hua hai", "kya hua tha",
      "tum theek ho", "tum thik ho",
      "aap theek ho", "aap thik ho",
      "kuch galat hai kya", "kuch galat hai",
      "bore ho", "bore ho kya", "boring",
      "bored ho", "bore ho rahi", "bore ho raha",
      "happy ho", "happy ho kya",
      "khush ho", "khush ho kya",
      "udaas ho", "udaas ho kya",
      "udaas", "udasi",
      "akela feel ho raha", "akeli feel ho rahi",
      "tanha lag raha", "akela lag raha",
    ],
  },
  {
    intent: "recharge",
    utterances: [
      "recharge karo", "recharge kar",
      "recharge kar do", "recharge karwa do",
      "recharge karwao", "recharge karwa",
      "coins chahiye", "coin chahiye", "coins do",
      "paisa chahiye", "paise chahiye",
      "paise do", "paisa do", "paise de do",
      "paise de", "paisa de do na",
      "wallet me coins nahi", "wallet khaali hai",
      "balance nahi hai", "balance kam hai",
      "low balance", "low coins",
      "coins khatam", "coins khatam ho gaye",
      "paisa khatam", "money khatam",
      "recharge ka option", "recharge kaise karein",
      "kaise recharge karein", "kaise karu recharge",
      "recharge ki link", "recharge link",
      "plan lena hai", "plan le lo",
      "vip le lo", "vip lena hai", "vip kaise",
      "vip chahiye", "vip plan", "vip kya hai",
      "vip ka kya fayda", "vip kya milta",
      "subscription kaise", "subscription chahiye",
      "subscription lena", "premium chahiye",
      "premium plan", "premium kaise le",
      "free coins kaise", "free coins chahiye",
      "daily check in", "daily reward", "daily bonus",
      "claim bonus", "bonus kaise milega",
      "coins kam pad gaye", "coins kam hai",
    ],
  },
  {
    intent: "joke",
    utterances: [
      "haha", "hahaha", "lol", "lmao", "rofl", "hehe",
      "haha mazak", "mazak kar rahe ho", "mazak kar rahi ho",
      "mazak karo", "mazak kar", "joke sunao",
      "ek joke sunao", "kuch funny batao",
      "has ke marungi", "has ke mara", "pet dard ho gaya",
      "very funny", "funny ho", "funny hai",
      "you're funny", "tum funny ho", "tum mazedaar ho",
      "mazedaar", "mazaak", "mazaak ud gaya",
      "maza aa gaya", "kya baat hai", "kya baat",
      "achha joke", "achha mazak", "ek aur sunao",
      "ek aur batao", "aur sunao", "aur batao",
      "sunao kuch", "batao kuch funny",
      "batao kuch maza", "kuch mazedaar batao",
      "kuch hasata hua batao", "kuch hasi wala batao",
      "kuch funny story", "ek kahani sunao",
      "kahani sunao", "sunno kahani", "sunna kahani",
      "funny kahani", "comedy sunao", "comedy karo",
    ],
  },
  {
    intent: "fallback",
    utterances: [
      "achha", "hmm", "okay", "ok", "theek hai",
      "achha theek", "hmm accha", "achha accha",
      "matlab", "matlab kya", "matlab kya hai",
      "kya matlab", "kya matlab hai",
      "kuch nahi", "kuch nahi hua",
      "kuch nahi samjha", "samjha nahi", "samjhao",
      "samjha do", "explain karo", "explain kar do",
      "explain", "explain karein", "samjhao na",
      "kuch aur batao", "aur batao", "aur kya",
      "kuch aur", "aur kuch", "kuch aur kya",
      "phir", "phir kya", "phir kya hua",
      "phir batao", "phir se batao",
      "phir se kaho", "phir se", "dobara",
      "dobara batao", "dobara kaho",
      "fir se", "fir se batao",
      "huh", "huh?", "kya", "kya?",
      "kya?", "kya hua?", "kya hai ye",
      "kuch", "kuch hai", "kuch toh hai",
      "kuch toh hoga", "samajh nahi aaya",
      "samajh nahi", "samjhao", "samjhao zara",
      "kuch nahi pata", "kuch nahi malum",
      "kya baat hai", "kya baat kar rahe ho",
      "kuch smjhao", "samjh nahi aaya",
      "kya tha ye", "ye kya tha", "ye kya hai",
      "kuch samjhao", "kuch samjha do",
      "main kya karu", "main kya karein",
      "kya karu", "kya karein ab",
      "kuch suggest karo", "kuch batao na",
      "kuch idea do", "kuch plan batao",
      "kya soch", "kuch soch",
      "kuch bhi bolo", "kuch bhi batao",
      "thoda time laga", "time laga",
      "thoda der laga", "der laga",
      "thoda aur time", "thoda aur der",
      "time nahi mila", "der ho gayi",
      "time nahi", "der ho gayi",
      "soch raha hu", "soch rahi hu",
      "soch lo", "soch ke batao",
      "sochna hai", "sochna padega",
      "kuch soch raha hu", "kuch soch rahi hu",
    ],
  },
];
